services:
  app:
    image: blog
    container_name: blog
    build: 
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
    command: npm start
  db:
    image: mysql:latest
    container_name: blog-db
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=135792468jK
      - MYSQL_DATABASE=blog